export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const UPDATE_DATA = 'UPDATE_DATA'
export const SET_FILE_VIEW = 'SET_FILE_VIEW'
export const CONSTRUCT_FILETREE = 'CONSTRUCT_FILETREE';
export const TOGGLE_FOLDER = 'TOGGLE_FOLDER';
export const UPDATE_KEY = 'UPDATE_KEY';
export const ADD_IT_STATEMENTS = 'ADD_IT_STATEMENTS';