export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
// export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'

export const SET_FILE_VIEW = 'SET_FILE_VIEW'
export const UPDATE_KEY = 'UPDATE_KEY'
export const CONSTRUCT_FILETREE = 'CONSTRUCT_FILETREE';